# Generated by Django 5.2.16 on 2026-07-23 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_refreshtoken"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_key", models.CharField(max_length=320, unique=True)),
                ("failure_count", models.IntegerField()),
                ("first_failure_at", models.DateTimeField()),
                ("last_failure_at", models.DateTimeField()),
                (
                    "locked_until",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
            ],
            options={
                "db_table": "login_attempts",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="email_verified",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="verified_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.CreateModel(
            name="SingleUseToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("purpose", models.CharField(max_length=32)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.user"
                    ),
                ),
            ],
            options={
                "db_table": "single_use_tokens",
            },
        ),
    ]
