# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_stage5c_account_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(db_default="active", default="active", max_length=16),
        ),
    ]
