# Generated by Django 5.2.16 on 2026-07-23 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_stage13b_user_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.CharField(max_length=220, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("body_json", models.JSONField()),
                ("body_html", models.TextField()),
                (
                    "status",
                    models.CharField(
                        db_default="draft", default="draft", max_length=16
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blog_posts",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "blog_posts",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        db_default="visible", default="visible", max_length=16
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="blog_comments",
                        to="core.user",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comments",
                        to="core.blogpost",
                    ),
                ),
            ],
            options={
                "db_table": "blog_comments",
            },
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(fields=["status"], name="blog_posts_status_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["status"], name="blog_comments_status_idx"),
        ),
    ]
