# Generated by hand, matching 0001-0005's own convention (see
# core/models.py's Flag docstring and alembic/versions/0006_stage13c_
# moderation.py's own module docstring for the full rationale this
# mirrors -- reporter uses on_delete=SET_NULL, the one FK in this
# migration that isn't PROTECT/RESTRICT).

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_stage13d_blog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("target_type", models.CharField(db_index=True, max_length=16)),
                ("target_id", models.UUIDField(db_index=True)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(db_default="open", db_index=True, default="open", max_length=16),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "resolution_note",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_flags",
                        to="core.user",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resolved_flags",
                        to="core.user",
                    ),
                ),
            ],
            options={
                "db_table": "flags",
            },
        ),
        migrations.AddIndex(
            model_name="flag",
            index=models.Index(fields=["status", "target_type"], name="flags_status_target_type_idx"),
        ),
    ]
